
services:
  db:
    image: postgres:17.2-bookworm
    volumes:
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file: .env

  app:
    build: .
    volumes:
      - .:/home/payd/app
      - payd_venv:/home/payd/app/.venv 
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    dns:
      - 8.8.8.8
      - 8.8.4.4


volumes:
  payd_venv: