x-app-base: &app-base
  build: .
  volumes:
    - .:/home/payd/app
    - payd_media:/home/payd/app/media
    - payd_static:/home/payd/app/staticfiles
  networks:
    - payd_dev
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started
  environment:
    - UV_NO_DEV=0
    - DB_HOST=db
    - CELERY_BROKER_URL=redis://redis:6379/0
    - CELERY_RESULT_BACKEND=redis://redis:6379/0
  env_file: .env
  dns:
    - 8.8.8.8
    - 8.8.4.4

services:
  db:
    image: postgres:17.2-bookworm
    volumes:
      - payd_db:/var/lib/postgresql/data
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - payd_dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file: .env

  redis:
    image: redis:7.2.4-alpine
    volumes:
      - payd_redis:/data
    ports:
      - "6379:6379"
    networks:
      - payd_dev
    restart: unless-stopped

  app:
    <<: *app-base
    entrypoint: "./entrypoint.sh"
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  celery_worker:
    <<: *app-base
    entrypoint: ""
    command: celery -A payd worker -l info

  celery_beat:
    <<: *app-base
    entrypoint: ""
    command: celery -A payd beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

networks:
  payd_dev:
    external: true

volumes:
  payd_db:
  payd_venv:
  payd_redis:
  payd_media:
  payd_static: