services:
  db:
    image: postgres:17.2-bookworm
    volumes:
      - payd_dev:/var/lib/postgresql/data
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file: .env
    networks:
      - payd_dev

  payd:
    build: .
    volumes:
      - .:/home/payd/app
      - payd_venv:/home/payd/app/.venv
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    networks:
      - payd_dev 
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  payd_dev:
    external: true

volumes:
  payd_dev:
  payd_venv: